/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roommate.status;
import java.awt.event.*;
import java.util.Scanner;
import java.net.URL;
import java.net.URLConnection;
import java.io.PrintStream;
import java.io.File;

/**
 *
 * @author Daniel
 */
public class window extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form window
     */
    public window() {
        initComponents();
        this.addActionListeners();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoTa = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roommate Staue");

        StatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avaliable", "Busy", "Do Not Disturb", "Out" }));

        memoTa.setColumns(20);
        memoTa.setRows(5);
        jScrollPane1.setViewportView(memoTa);

        submitBtn.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(StatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(submitBtn)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void addActionListeners(){
       submitBtn.addActionListener(this);
   }
    
    public void actionPerformed(ActionEvent e){
       if(e.getSource() == this.submitBtn){
           try{
               Scanner sc = new Scanner(new File("../ip.txt"));
               String source = "java";
               String status = String.valueOf(this.StatusCombo.getSelectedItem());
               String memo = this.memoTa.getText();
               
               URL url = new URL("http://" + sc.nextLine().trim() + "/editStatus.php");
               URLConnection con = url.openConnection();
               con.setDoOutput(true);
               PrintStream ps = new PrintStream(con.getOutputStream());
               ps.print("&source=" + source);
               ps.print("&general=" + status);
               ps.print("&memo=" + memo);
               
               con.getInputStream();
               ps.close();
               
           }catch(Exception error){
               System.out.println(error.getMessage());
           }
       }
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StatusCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memoTa;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
